"""
Event Bus schemas - Redis pub/sub internal events.
Defines the JSON contract between the backend trading engine and frontend.

All timestamps are in UTC ISO-8601 format.
NQ hardcoded constants: tick_size=0.25, tick_value=$5, point_value=$20
"""
from pydantic import BaseModel, Field
from datetime import datetime
from typing import Literal, Optional


# NQ Futures constants (hardcoded)
NQ_TICK_SIZE = 0.25
NQ_TICK_VALUE = 5.00
NQ_POINT_VALUE = 20.00


class BaseEvent(BaseModel):
    """
    Base event schema for all Event Bus events.

    All events must have:
    - channel: Redis pub/sub channel name
    - ts: Timestamp in UTC
    - bot_id: Identifier for the trading bot that generated the event
    """
    channel: str
    ts: datetime
    bot_id: str


class CandleEvent(BaseEvent):
    """
    New candle completed event.

    Channel format: `nqhub.candle.{timeframe}`
    Example: `nqhub.candle.1min`, `nqhub.candle.5min`
    """
    timeframe: str = Field(..., description="Timeframe (e.g., '1min', '5min', '1h')")
    open: float = Field(..., description="Open price")
    high: float = Field(..., description="High price")
    low: float = Field(..., description="Low price")
    close: float = Field(..., description="Close price")
    volume: int = Field(..., description="Total volume")
    delta: int = Field(..., description="Delta (buy volume - sell volume)")
    poc: float = Field(..., description="Point of Control price")


class PatternEvent(BaseEvent):
    """
    ICT pattern detected event.

    Channel format: `nqhub.pattern.{type}`
    Example: `nqhub.pattern.fvg`, `nqhub.pattern.ob`, `nqhub.pattern.lp`

    Pattern types:
    - fvg: Fair Value Gap
    - ob: Order Block
    - lp: Liquidity Pool
    - bb: Breaker Block
    """
    pattern_type: str = Field(..., description="Pattern type: 'fvg' | 'ob' | 'lp' | 'bb'")
    direction: str = Field(..., description="Pattern direction: 'bullish' | 'bearish'")
    top: float = Field(..., description="Top of pattern zone")
    bottom: float = Field(..., description="Bottom of pattern zone")
    timeframe: str = Field(..., description="Timeframe where pattern was detected")
    status: str = Field(..., description="Pattern status: 'active' | 'mitigated' | 'broken'")


class RiskCheckEvent(BaseEvent):
    """
    Pre-trade risk check result event.

    Channel: `nqhub.risk.check`

    Generated by RiskManager before allowing order submission.
    If trigger_kill_switch=True, the system will activate the kill switch.
    """
    check_name: str = Field(..., description="Name of the risk check performed")
    result: Literal['PASSED', 'REJECTED'] = Field(..., description="Check result")
    reason: str = Field(default="", description="Reason for rejection (if applicable)")
    trigger_kill_switch: bool = Field(default=False, description="Whether to activate kill switch")
    account_balance: float = Field(..., description="Current account balance")
    current_pnl: float = Field(..., description="Current profit/loss")


class KillSwitchEvent(BaseEvent):
    """
    Kill switch activated event (HIGHEST PRIORITY).

    Channel: `nqhub.risk.kill_switch`

    This is the only channel with special priority - always processed first.
    Generated when the kill switch is activated either manually or by circuit breaker.
    """
    scope: Literal['per_bot', 'global'] = Field(..., description="Kill switch scope")
    reason: str = Field(..., description="Reason for activation")
    triggered_by: Literal['manual', 'circuit_breaker'] = Field(..., description="What triggered the kill switch")
    positions_closed: int = Field(..., description="Number of positions closed")
    orders_cancelled: int = Field(..., description="Number of orders cancelled")


class OrderEvent(BaseEvent):
    """
    Order status change event.

    Channel format: `exec.order.{status}`
    Example: `exec.order.submitted`, `exec.order.filled`, `exec.order.rejected`

    Statuses:
    - SUBMITTED: Order sent to broker
    - FILLED: Order fully executed
    - REJECTED: Order rejected by broker
    - CANCELLED: Order cancelled
    """
    order_id: str = Field(..., description="Internal order UUID")
    client_order_id: str = Field(..., description="Client order identifier")
    broker_order_id: Optional[str] = Field(default=None, description="Broker's order ID (from Rithmic/etc)")
    bracket_role: Optional[str] = Field(default=None, description="Bracket role: 'ENTRY' | 'TP' | 'SL'")
    side: str = Field(..., description="Order side: 'BUY' | 'SELL'")
    contracts: int = Field(..., description="Number of contracts")
    fill_price: Optional[float] = Field(default=None, description="Fill price (only for filled orders)")
    status: str = Field(..., description="Order status: 'SUBMITTED' | 'FILLED' | 'REJECTED' | 'CANCELLED'")


class PositionEvent(BaseEvent):
    """
    Position update event.

    Channel: `exec.position.update`

    Generated whenever an open position is updated (price change, PNL change, etc).
    """
    symbol: str = Field(..., description="Symbol (e.g., 'NQ')")
    side: str = Field(..., description="Position side: 'LONG' | 'SHORT'")
    contracts: int = Field(..., description="Number of contracts in position")
    entry_price: float = Field(..., description="Average entry price")
    current_price: float = Field(..., description="Current market price")
    unrealized_pnl: float = Field(..., description="Unrealized P&L in dollars")
    unrealized_pnl_ticks: float = Field(..., description="Unrealized P&L in ticks (unrealized_pnl / tick_value)")


# Export all schemas
__all__ = [
    'BaseEvent',
    'CandleEvent',
    'PatternEvent',
    'RiskCheckEvent',
    'KillSwitchEvent',
    'OrderEvent',
    'PositionEvent',
    'NQ_TICK_SIZE',
    'NQ_TICK_VALUE',
    'NQ_POINT_VALUE',
]
