"""
Tests for Research & Backtesting OpenAPI Spec (AUT-363)

Verifies that the OpenAPI spec is properly generated by FastAPI
and includes all required endpoints with correct schemas.

Tests:
1. test_openapi_spec_includes_all_7_endpoints
2. test_backtest_run_accepts_correct_body
3. test_optimize_validates_method_enum
4. test_strategies_endpoint_returns_list
5. test_strategy_register_validates_type
6. test_spec_exports_to_yaml
"""
import pytest
import json
import yaml
from pathlib import Path
from fastapi.testclient import TestClient
from openapi_spec_validator import validate_spec
from openapi_spec_validator.validation.exceptions import OpenAPIValidationError


# ============= Fixtures =============

@pytest.fixture
def app():
    """Create FastAPI app instance for testing"""
    from fastapi import FastAPI
    from app.api.v1.research.routes import router

    app = FastAPI(
        title="NQHUB Research & Backtesting API",
        description="Backtesting engine and strategy management",
        version="2.0.0"
    )
    app.include_router(router)
    return app


@pytest.fixture
def client(app):
    """Create test client"""
    return TestClient(app)


@pytest.fixture
def openapi_spec(app):
    """Get OpenAPI spec from FastAPI app"""
    return app.openapi()


# ============= Test 1: All 7 Endpoints Included =============

def test_openapi_spec_includes_all_7_endpoints(openapi_spec):
    """
    Test that OpenAPI spec includes all 7 required endpoints.

    Required endpoints:
    1. POST /research/backtest/run
    2. POST /research/backtest/results/import
    3. POST /research/backtest/optimize
    4. GET  /research/backtest/screener
    5. GET  /research/strategies
    6. POST /research/strategies/register
    7. POST /research/strategies/validate
    """
    paths = openapi_spec.get("paths", {})

    required_endpoints = {
        "/research/backtest/run": ["post"],
        "/research/backtest/results/import": ["post"],
        "/research/backtest/optimize": ["post"],
        "/research/backtest/screener": ["get"],
        "/research/strategies": ["get"],
        "/research/strategies/register": ["post"],
        "/research/strategies/validate": ["post"],
    }

    for endpoint, methods in required_endpoints.items():
        assert endpoint in paths, f"Endpoint {endpoint} not found in OpenAPI spec"

        for method in methods:
            assert method in paths[endpoint], \
                f"Method {method.upper()} not found for endpoint {endpoint}"

    # Verify exactly 7 endpoints (no extras)
    assert len(paths) == 7, \
        f"Expected exactly 7 endpoints, found {len(paths)}: {list(paths.keys())}"


# ============= Test 2: Backtest Run Accepts Correct Body =============

def test_backtest_run_accepts_correct_body(openapi_spec):
    """
    Test that POST /backtest/run accepts the correct request body schema.

    Required fields:
    - strategy_id: string
    - timeframe: string
    - start_date: date
    - end_date: date
    - commission: float (default 0.0002)
    - slippage: float (default 0.0001)
    - initial_capital: float (default 25000.0)
    - parameters: dict (default {})
    """
    endpoint = "/research/backtest/run"
    spec = openapi_spec["paths"][endpoint]["post"]

    # Verify request body exists
    assert "requestBody" in spec, "Request body not defined for /backtest/run"

    request_body = spec["requestBody"]["content"]["application/json"]["schema"]

    # Get schema reference and resolve it
    if "$ref" in request_body:
        schema_name = request_body["$ref"].split("/")[-1]
        schema = openapi_spec["components"]["schemas"][schema_name]
    else:
        schema = request_body

    # Verify required fields
    required_fields = ["strategy_id", "timeframe", "start_date", "end_date"]
    assert "required" in schema, "Required fields not specified in schema"

    for field in required_fields:
        assert field in schema["required"], \
            f"Field '{field}' should be required in BacktestRunRequest"

    # Verify properties
    properties = schema["properties"]

    assert "strategy_id" in properties
    assert properties["strategy_id"]["type"] == "string"

    assert "timeframe" in properties
    assert properties["timeframe"]["type"] == "string"

    assert "initial_capital" in properties
    assert properties["initial_capital"]["type"] == "number"
    # Verify default is Apex $25K
    assert properties["initial_capital"].get("default") == 25000.0, \
        "initial_capital default should be 25000.0 (Apex account)"

    assert "commission" in properties
    assert properties["commission"]["type"] == "number"
    assert properties["commission"].get("default") == 0.0002

    assert "slippage" in properties
    assert properties["slippage"]["type"] == "number"
    assert properties["slippage"].get("default") == 0.0001

    assert "parameters" in properties
    assert properties["parameters"]["type"] == "object"


# ============= Test 3: Optimize Validates Method Enum =============

def test_optimize_validates_method_enum(openapi_spec):
    """
    Test that POST /backtest/optimize validates method enum.

    Valid values: "grid_search" | "walk_forward"
    """
    endpoint = "/research/backtest/optimize"
    spec = openapi_spec["paths"][endpoint]["post"]

    request_body = spec["requestBody"]["content"]["application/json"]["schema"]

    # Resolve schema reference
    if "$ref" in request_body:
        schema_name = request_body["$ref"].split("/")[-1]
        schema = openapi_spec["components"]["schemas"][schema_name]
    else:
        schema = request_body

    # Verify method field exists
    assert "method" in schema["properties"], "method field not found in OptimizeRequest"

    method_field = schema["properties"]["method"]

    # Verify enum constraint
    # Note: Pydantic may use "enum" or "anyOf" with "const" for enums
    # Check for examples which should include the valid values
    if "examples" in method_field:
        examples = method_field["examples"]
        assert "grid_search" in examples, "grid_search should be a valid method"
        assert "walk_forward" in examples, "walk_forward should be a valid method"
    elif "enum" in method_field:
        assert "grid_search" in method_field["enum"]
        assert "walk_forward" in method_field["enum"]

    # Verify method is required
    assert "method" in schema["required"], "method should be required in OptimizeRequest"


# ============= Test 4: Strategies Endpoint Returns List =============

def test_strategies_endpoint_returns_list(openapi_spec):
    """
    Test that GET /strategies returns a list of StrategySchema.

    Response should be array of strategy objects.
    """
    endpoint = "/research/strategies"
    spec = openapi_spec["paths"][endpoint]["get"]

    # Verify response schema
    assert "responses" in spec
    assert "200" in spec["responses"], "200 response not defined for GET /strategies"

    response_schema = spec["responses"]["200"]["content"]["application/json"]["schema"]

    # Response should be an array
    assert response_schema["type"] == "array", \
        "GET /strategies should return an array"

    # Array items should be StrategySchema
    items = response_schema["items"]

    if "$ref" in items:
        schema_name = items["$ref"].split("/")[-1]
        assert schema_name == "StrategySchema", \
            f"Array items should be StrategySchema, got {schema_name}"

        # Verify StrategySchema has required fields
        strategy_schema = openapi_spec["components"]["schemas"]["StrategySchema"]
        required_fields = ["id", "name", "version", "type", "description",
                          "parameters_schema", "is_active"]

        for field in required_fields:
            assert field in strategy_schema["properties"], \
                f"Field '{field}' missing from StrategySchema"


# ============= Test 5: Strategy Register Validates Type =============

def test_strategy_register_validates_type(openapi_spec):
    """
    Test that POST /strategies/register validates strategy type.

    Valid types: "rule_based" | "ml" | "dl" | "rl"
    """
    endpoint = "/research/strategies/register"
    spec = openapi_spec["paths"][endpoint]["post"]

    request_body = spec["requestBody"]["content"]["application/json"]["schema"]

    # Resolve schema reference
    if "$ref" in request_body:
        schema_name = request_body["$ref"].split("/")[-1]
        schema = openapi_spec["components"]["schemas"][schema_name]
    else:
        schema = request_body

    # Verify type field exists
    assert "type" in schema["properties"], "type field not found in StrategyRegisterRequest"

    type_field = schema["properties"]["type"]

    # Verify examples include valid types
    if "examples" in type_field:
        examples = type_field["examples"]
        valid_types = ["rule_based", "ml", "dl", "rl"]
        for valid_type in valid_types:
            assert valid_type in examples, \
                f"{valid_type} should be a valid strategy type"
    elif "enum" in type_field:
        assert set(type_field["enum"]) == {"rule_based", "ml", "dl", "rl"}

    # Verify type is required
    assert "type" in schema["required"], "type should be required in StrategyRegisterRequest"


# ============= Test 6: Spec Exports to YAML =============

def test_spec_exports_to_yaml(app, tmp_path):
    """
    Test that OpenAPI spec can be exported to YAML and validates.

    Validates:
    1. Spec can be converted to YAML
    2. YAML is valid OpenAPI 3.0 spec
    3. Passes openapi-spec-validator
    """
    # Get OpenAPI spec
    spec = app.openapi()

    # Export to YAML
    yaml_path = tmp_path / "research-backtesting.yaml"

    with open(yaml_path, "w") as f:
        yaml.dump(spec, f, default_flow_style=False, sort_keys=False)

    # Verify file was created
    assert yaml_path.exists(), "YAML file was not created"

    # Read back and verify valid YAML
    with open(yaml_path, "r") as f:
        loaded_spec = yaml.safe_load(f)

    assert loaded_spec is not None, "Failed to load YAML"
    assert "openapi" in loaded_spec, "OpenAPI version not found in spec"
    assert "paths" in loaded_spec, "Paths not found in spec"

    # Verify OpenAPI version
    assert loaded_spec["openapi"].startswith("3."), \
        f"Expected OpenAPI 3.x, got {loaded_spec['openapi']}"

    # Validate spec with openapi-spec-validator
    try:
        validate_spec(loaded_spec)
    except OpenAPIValidationError as e:
        pytest.fail(f"OpenAPI spec validation failed: {e}")

    # Verify all 7 endpoints are in the exported spec
    assert len(loaded_spec["paths"]) == 7, \
        f"Expected 7 endpoints in exported spec, found {len(loaded_spec['paths'])}"


# ============= Additional Validation Tests =============

def test_all_endpoints_have_response_models(openapi_spec):
    """
    Verify that all endpoints have proper response models defined.
    """
    paths = openapi_spec["paths"]

    for path, methods in paths.items():
        for method, spec in methods.items():
            assert "responses" in spec, \
                f"No responses defined for {method.upper()} {path}"

            assert "200" in spec["responses"], \
                f"No 200 response defined for {method.upper()} {path}"

            response = spec["responses"]["200"]
            assert "content" in response, \
                f"No content defined for 200 response of {method.upper()} {path}"


def test_all_schemas_have_examples(openapi_spec):
    """
    Verify that all request/response schemas have examples for documentation.
    """
    schemas = openapi_spec.get("components", {}).get("schemas", {})

    # Key schemas that should have examples
    required_examples = [
        "BacktestRunRequest",
        "BacktestRunResponse",
        "BacktestResultsSchema",
        "OptimizeRequest",
        "StrategySchema",
        "StrategyRegisterRequest",
    ]

    for schema_name in required_examples:
        assert schema_name in schemas, f"Schema {schema_name} not found in components"

        schema = schemas[schema_name]

        # Check for example in schema or properties
        has_example = (
            "example" in schema or
            "examples" in schema or
            any("example" in prop or "examples" in prop
                for prop in schema.get("properties", {}).values())
        )

        assert has_example, \
            f"Schema {schema_name} should have examples for documentation"


def test_spec_validates_with_openapi_validator(openapi_spec):
    """
    Final validation: Ensure spec passes openapi-spec-validator.
    """
    try:
        validate_spec(openapi_spec)
    except OpenAPIValidationError as e:
        pytest.fail(f"OpenAPI spec validation failed: {e}")
